# FROM node:18-alpine AS builder
#
# WORKDIR /app
#
# COPY package.json package-lock.json ./
#
# RUN npm install
#
# COPY . .
#
# RUN npm run build
#
# FROM node:18-alpine
#
# WORKDIR /app
#
# RUN npm install -g serve
#
# COPY --from=builder /app/dist ./dist
#
# EXPOSE 5173
#
# CMD ["serve", "-s", "build", "-l", "5173"]

FROM node:18 AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build
RUN ls -la /app/dist
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

