version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app  # Для Hot Reload
      - /app/node_modules  # Игнорируем node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true  # Интерактивный режим
    tty: true         # Цветные логи
    depends_on:
      - api  # Зависимость от API

  api:
    build: ./api
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure  # Добавлено для автоматического перезапуска

  bot:
    build: ./bot
    env_file: .env  # Подключаем корневой .env
    depends_on:
      - api

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password  # Теперь совпадает с DATABASE_URL
      - POSTGRES_DB=flashcards
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:  # Добавлен healthcheck
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
