FROM python:3.10-slim
WORKDIR /app

RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
EXPOSE 8080

COPY wait-for-postgres.sh .
RUN chmod +x wait-for-postgres.sh

CMD ["sh wait-for-postgres.sh", "postgres", "5432", "postgres", "1234", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]